// Comprehensive list of countries/regions sorted by approximate GDP/Economic importance
// Specific political overrides applied for China regions as per requirements

export const COUNTRIES = [
  // 1. China & Regions (Top Fixed)
  { value: '中国', label: '中国', flag: '🇨🇳', code: '+86', en: 'China', py: 'zhongguo' },
  { value: '中国香港', label: '中国香港', flag: '🇭🇰', code: '+852', en: 'Hong Kong', py: 'zhongguoxianggang' },
  { value: '中国澳门', label: '中国澳门', flag: '🇲🇴', code: '+853', en: 'Macau', py: 'zhongguoaomen' },
  { value: '中国台湾', label: '中国台湾', flag: '🇨🇳', code: '+886', en: 'Taiwan', py: 'zhongguotaiwan' },

  // 2. Top Economies (Approximate GDP Descending)
  { value: '美国', label: '美国', flag: '🇺🇸', code: '+1', en: 'United States', py: 'meiguo' },
  { value: '德国', label: '德国', flag: '🇩🇪', code: '+49', en: 'Germany', py: 'deguo' },
  { value: '日本', label: '日本', flag: '🇯🇵', code: '+81', en: 'Japan', py: 'riben' },
  { value: '印度', label: '印度', flag: '🇮🇳', code: '+91', en: 'India', py: 'yindu' },
  { value: '英国', label: '英国', flag: '🇬🇧', code: '+44', en: 'United Kingdom', py: 'yingguo' },
  { value: '法国', label: '法国', flag: '🇫🇷', code: '+33', en: 'France', py: 'faguo' },
  { value: '意大利', label: '意大利', flag: '🇮🇹', code: '+39', en: 'Italy', py: 'yidali' },
  { value: '巴西', label: '巴西', flag: '🇧🇷', code: '+55', en: 'Brazil', py: 'baxi' },
  { value: '加拿大', label: '加拿大', flag: '🇨🇦', code: '+1', en: 'Canada', py: 'jianada' },
  { value: '俄罗斯', label: '俄罗斯', flag: '🇷🇺', code: '+7', en: 'Russia', py: 'eluosi' },
  { value: '韩国', label: '韩国', flag: '🇰🇷', code: '+82', en: 'South Korea', py: 'hanguo' },
  { value: '澳大利亚', label: '澳大利亚', flag: '🇦🇺', code: '+61', en: 'Australia', py: 'aodaliya' },
  { value: '墨西哥', label: '墨西哥', flag: '🇲🇽', code: '+52', en: 'Mexico', py: 'moxige' },
  { value: '西班牙', label: '西班牙', flag: '🇪🇸', code: '+34', en: 'Spain', py: 'xibanya' },
  { value: '印度尼西亚', label: '印度尼西亚', flag: '🇮🇩', code: '+62', en: 'Indonesia', py: 'yindunixiya' },
  { value: '荷兰', label: '荷兰', flag: '🇳🇱', code: '+31', en: 'Netherlands', py: 'helan' },
  { value: '土耳其', label: '土耳其', flag: '🇹🇷', code: '+90', en: 'Turkey', py: 'tuerqi' },
  { value: '沙特阿拉伯', label: '沙特阿拉伯', flag: '🇸🇦', code: '+966', en: 'Saudi Arabia', py: 'shatealabo' },
  { value: '瑞士', label: '瑞士', flag: '🇨🇭', code: '+41', en: 'Switzerland', py: 'ruishi' },
  { value: '新加坡', label: '新加坡', flag: '🇸🇬', code: '+65', en: 'Singapore', py: 'xinjiapo' },
  { value: '瑞典', label: '瑞典', flag: '🇸🇪', code: '+46', en: 'Sweden', py: 'ruidian' },
  { value: '波兰', label: '波兰', flag: '🇵🇱', code: '+48', en: 'Poland', py: 'bolan' },
  { value: '阿根廷', label: '阿根廷', flag: '🇦🇷', code: '+54', en: 'Argentina', py: 'agenting' },
  { value: '比利时', label: '比利时', flag: '🇧🇪', code: '+32', en: 'Belgium', py: 'bilishi' },
  { value: '泰国', label: '泰国', flag: '🇹🇭', code: '+66', en: 'Thailand', py: 'taiguo' },
  { value: '奥地利', label: '奥地利', flag: '🇦🇹', code: '+43', en: 'Austria', py: 'aodili' },
  { value: '伊朗', label: '伊朗', flag: '🇮🇷', code: '+98', en: 'Iran', py: 'yilang' },
  { value: '阿联酋', label: '阿联酋', flag: '🇦🇪', code: '+971', en: 'United Arab Emirates', py: 'alianqiu' },
  { value: '挪威', label: '挪威', flag: '🇳🇴', code: '+47', en: 'Norway', py: 'nuowei' },
  { value: '尼日利亚', label: '尼日利亚', flag: '🇳🇬', code: '+234', en: 'Nigeria', py: 'niriliya' },
  { value: '以色列', label: '以色列', flag: '🇮🇱', code: '+972', en: 'Israel', py: 'yiselie' },
  { value: '爱尔兰', label: '爱尔兰', flag: '🇮🇪', code: '+353', en: 'Ireland', py: 'aierlan' },
  { value: '埃及', label: '埃及', flag: '🇪🇬', code: '+20', en: 'Egypt', py: 'aiji' },
  { value: '丹麦', label: '丹麦', flag: '🇩🇰', code: '+45', en: 'Denmark', py: 'danmai' },
  { value: '菲律宾', label: '菲律宾', flag: '🇵🇭', code: '+63', en: 'Philippines', py: 'felvbin' },
  { value: '马来西亚', label: '马来西亚', flag: '🇲🇾', code: '+60', en: 'Malaysia', py: 'malaixiya' },
  { value: '南非', label: '南非', flag: '🇿🇦', code: '+27', en: 'South Africa', py: 'nanfei' },
  { value: '越南', label: '越南', flag: '🇻🇳', code: '+84', en: 'Vietnam', py: 'yuenan' },
  { value: '孟加拉国', label: '孟加拉国', flag: '🇧🇩', code: '+880', en: 'Bangladesh', py: 'mengjialaguo' },
  { value: '巴基斯坦', label: '巴基斯坦', flag: '🇵🇰', code: '+92', en: 'Pakistan', py: 'bajisitan' },
  { value: '智利', label: '智利', flag: '🇨🇱', code: '+56', en: 'Chile', py: 'zhili' },
  { value: '芬兰', label: '芬兰', flag: '🇫🇮', code: '+358', en: 'Finland', py: 'fenlan' },
  { value: '哥伦比亚', label: '哥伦比亚', flag: '🇨🇴', code: '+57', en: 'Colombia', py: 'gelunbiya' },
  { value: '罗马尼亚', label: '罗马尼亚', flag: '🇷🇴', code: '+40', en: 'Romania', py: 'luomaniya' },
  { value: '捷克', label: '捷克', flag: '🇨🇿', code: '+420', en: 'Czech Republic', py: 'jieke' },
  { value: '葡萄牙', label: '葡萄牙', flag: '🇵🇹', code: '+351', en: 'Portugal', py: 'putaoya' },
  { value: '新西兰', label: '新西兰', flag: '🇳🇿', code: '+64', en: 'New Zealand', py: 'xinxilan' },
  { value: '秘鲁', label: '秘鲁', flag: '🇵🇪', code: '+51', en: 'Peru', py: 'milu' },
  { value: '希腊', label: '希腊', flag: '🇬🇷', code: '+30', en: 'Greece', py: 'xila' },
  { value: '哈萨克斯坦', label: '哈萨克斯坦', flag: '🇰🇿', code: '+7', en: 'Kazakhstan', py: 'hasakesitan' },
  { value: '乌克兰', label: '乌克兰', flag: '🇺🇦', code: '+380', en: 'Ukraine', py: 'wukelan' },
  { value: '匈牙利', label: '匈牙利', flag: '🇭🇺', code: '+36', en: 'Hungary', py: 'xiongyali' },
  { value: '卡塔尔', label: '卡塔尔', flag: '🇶🇦', code: '+974', en: 'Qatar', py: 'kataer' },
  { value: '阿尔及利亚', label: '阿尔及利亚', flag: '🇩🇿', code: '+213', en: 'Algeria', py: 'aerjiliya' },
  { value: '科威特', label: '科威特', flag: '🇰🇼', code: '+965', en: 'Kuwait', py: 'keweite' },
  { value: '摩洛哥', label: '摩洛哥', flag: '🇲🇦', code: '+212', en: 'Morocco', py: 'moluoge' },
  { value: '斯洛伐克', label: '斯洛伐克', flag: '🇸🇰', code: '+421', en: 'Slovakia', py: 'siluofake' },
  { value: '古巴', label: '古巴', flag: '🇨🇺', code: '+53', en: 'Cuba', py: 'guba' },
  { value: '厄瓜多尔', label: '厄瓜多尔', flag: '🇪🇨', code: '+593', en: 'Ecuador', py: 'eguaduoer' },
  { value: '埃塞俄比亚', label: '埃塞俄比亚', flag: '🇪🇹', code: '+251', en: 'Ethiopia', py: 'aisaiebiya' },
  { value: '肯尼亚', label: '肯尼亚', flag: '🇰🇪', code: '+254', en: 'Kenya', py: 'kenniya' },
  { value: '安哥拉', label: '安哥拉', flag: '🇦🇴', code: '+244', en: 'Angola', py: 'angela' },
  { value: '多米尼加共和国', label: '多米尼加共和国', flag: '🇩🇴', code: '+1-809', en: 'Dominican Republic', py: 'duominijiagongheguo' },
  { value: '阿曼', label: '阿曼', flag: '🇴🇲', code: '+968', en: 'Oman', py: 'aman' },
  { value: '危地马拉', label: '危地马拉', flag: '🇬🇹', code: '+502', en: 'Guatemala', py: 'weidimala' },
  { value: '保加利亚', label: '保加利亚', flag: '🇧🇬', code: '+359', en: 'Bulgaria', py: 'baojialiya' },
  { value: '卢森堡', label: '卢森堡', flag: '🇱🇺', code: '+352', en: 'Luxembourg', py: 'lusenbao' },
  { value: '委内瑞拉', label: '委内瑞拉', flag: '🇻🇪', code: '+58', en: 'Venezuela', py: 'weineiruela' },
  { value: '乌兹别克斯坦', label: '乌兹别克斯坦', flag: '🇺🇿', code: '+998', en: 'Uzbekistan', py: 'wuzibekesitan' },
  { value: '白俄罗斯', label: '白俄罗斯', flag: '🇧🇾', code: '+375', en: 'Belarus', py: 'baieluosi' },
  { value: '坦桑尼亚', label: '坦桑尼亚', flag: '🇹🇿', code: '+255', en: 'Tanzania', py: 'tansanniya' },
  { value: '土库曼斯坦', label: '土库曼斯坦', flag: '🇹🇲', code: '+993', en: 'Turkmenistan', py: 'tukumansitan' },
  { value: '克罗地亚', label: '克罗地亚', flag: '🇭🇷', code: '+385', en: 'Croatia', py: 'keluodiya' },
  { value: '立陶宛', label: '立陶宛', flag: '🇱🇹', code: '+370', en: 'Lithuania', py: 'litaowan' },
  { value: '哥斯达黎加', label: '哥斯达黎加', flag: '🇨🇷', code: '+506', en: 'Costa Rica', py: 'gesidalijia' },
  { value: '塞尔维亚', label: '塞尔维亚', flag: '🇷🇸', code: '+381', en: 'Serbia', py: 'saierweiya' },
  { value: '乌拉圭', label: '乌拉圭', flag: '🇺🇾', code: '+598', en: 'Uruguay', py: 'wulagui' },
  { value: '巴拿马', label: '巴拿马', flag: '🇵🇦', code: '+507', en: 'Panama', py: 'banama' },
  { value: '斯洛文尼亚', label: '斯洛文尼亚', flag: '🇸🇮', code: '+386', en: 'Slovenia', py: 'siluowenniya' },
  { value: '阿塞拜疆', label: '阿塞拜疆', flag: '🇦🇿', code: '+994', en: 'Azerbaijan', py: 'asaibaijiang' },
  { value: '刚果（金）', label: '刚果（金）', flag: '🇨🇩', code: '+243', en: 'DR Congo', py: 'gangguojin' },
  { value: '科特迪瓦', label: '科特迪瓦', flag: '🇨🇮', code: '+225', en: 'Ivory Coast', py: 'keteidiwa' },
  { value: '巴林', label: '巴林', flag: '🇧🇭', code: '+973', en: 'Bahrain', py: 'balin' },
  { value: '约旦', label: '约旦', flag: '🇯🇴', code: '+962', en: 'Jordan', py: 'yuedan' },
  { value: '喀麦隆', label: '喀麦隆', flag: '🇨🇲', code: '+237', en: 'Cameroon', py: 'kamailong' },
  { value: '突尼斯', label: '突尼斯', flag: '🇹🇳', code: '+216', en: 'Tunisia', py: 'tunisi' },
  { value: '玻利维亚', label: '玻利维亚', flag: '🇧🇴', code: '+591', en: 'Bolivia', py: 'boliweiya' },
  { value: '乌干达', label: '乌干达', flag: '🇺🇬', code: '+256', en: 'Uganda', py: 'wuganda' },
  { value: '尼泊尔', label: '尼泊尔', flag: '🇳🇵', code: '+977', en: 'Nepal', py: 'niboer' },
  { value: '爱沙尼亚', label: '爱沙尼亚', flag: '🇪🇪', code: '+372', en: 'Estonia', py: 'aishaniya' },
  { value: '拉脱维亚', label: '拉脱维亚', flag: '🇱🇻', code: '+371', en: 'Latvia', py: 'latuoweiya' },
  { value: '巴拉圭', label: '巴拉圭', flag: '🇵🇾', code: '+595', en: 'Paraguay', py: 'balagui' },
  { value: '津巴布韦', label: '津巴布韦', flag: '🇿🇼', code: '+263', en: 'Zimbabwe', py: 'jinbabuwei' },
  { value: '赞比亚', label: '赞比亚', flag: '🇿🇲', code: '+260', en: 'Zambia', py: 'zanbiya' },
  { value: '冰岛', label: '冰岛', flag: '🇮🇸', code: '+354', en: 'Iceland', py: 'bingdao' },
  { value: '萨尔瓦多', label: '萨尔瓦多', flag: '🇸🇻', code: '+503', en: 'El Salvador', py: 'saerwaduo' },
  { value: '洪都拉斯', label: '洪都拉斯', flag: '🇭🇳', code: '+504', en: 'Honduras', py: 'hongdulasi' },
  { value: '塞内加尔', label: '塞内加尔', flag: '🇸🇳', code: '+221', en: 'Senegal', py: 'saineijiaer' },
  { value: '柬埔寨', label: '柬埔寨', flag: '🇰🇭', code: '+855', en: 'Cambodia', py: 'jianpuzhai' },
  { value: '塞浦路斯', label: '塞浦路斯', flag: '🇨🇾', code: '+357', en: 'Cyprus', py: 'saipulusi' },
  { value: '波斯尼亚和黑塞哥维那', label: '波斯尼亚和黑塞哥维那', flag: '🇧🇦', code: '+387', en: 'Bosnia and Herzegovina', py: 'bosiniya' },
  { value: '格鲁吉亚', label: '格鲁吉亚', flag: '🇬🇪', code: '+995', en: 'Georgia', py: 'gelujiya' },
  { value: '黎巴嫩', label: '黎巴嫩', flag: '🇱🇧', code: '+961', en: 'Lebanon', py: 'libanen' },
  { value: '也门', label: '也门', flag: '🇾🇪', code: '+967', en: 'Yemen', py: 'yemen' },
  { value: '蒙古', label: '蒙古', flag: '🇲🇳', code: '+976', en: 'Mongolia', py: 'menggu' },
  { value: '阿富汗', label: '阿富汗', flag: '🇦🇫', code: '+93', en: 'Afghanistan', py: 'afuhan' },
  { value: '亚美尼亚', label: '亚美尼亚', flag: '🇦🇲', code: '+374', en: 'Armenia', py: 'yameiniya' },
  { value: '莫桑比克', label: '莫桑比克', flag: '🇲🇿', code: '+258', en: 'Mozambique', py: 'mosangbike' },
  { value: '博茨瓦纳', label: '博茨瓦纳', flag: '🇧🇼', code: '+267', en: 'Botswana', py: 'bociwana' },
  { value: '阿尔巴尼亚', label: '阿尔巴尼亚', flag: '🇦🇱', code: '+355', en: 'Albania', py: 'aerbaniya' },
  { value: '马里', label: '马里', flag: '🇲🇱', code: '+223', en: 'Mali', py: 'mali' },
  { value: '文莱', label: '文莱', flag: '🇧🇳', code: '+673', en: 'Brunei', py: 'wenlai' },
  { value: '尼加拉瓜', label: '尼加拉瓜', flag: '🇳🇮', code: '+505', en: 'Nicaragua', py: 'nijialagua' },
  { value: '老挝', label: '老挝', flag: '🇱🇦', code: '+856', en: 'Laos', py: 'laowo' },
  { value: '马达加斯加', label: '马达加斯加', flag: '🇲🇬', code: '+261', en: 'Madagascar', py: 'madajiasijia' },
  { value: '北马其顿', label: '北马其顿', flag: '🇲🇰', code: '+389', en: 'North Macedonia', py: 'beimaqidun' },
  { value: '牙买加', label: '牙买加', flag: '🇯🇲', code: '+1-876', en: 'Jamaica', py: 'yamaijia' },
  { value: '摩尔多瓦', label: '摩尔多瓦', flag: '🇲🇩', code: '+373', en: 'Moldova', py: 'moerduowa' },
  { value: '尼日尔', label: '尼日尔', flag: '🇳🇪', code: '+227', en: 'Niger', py: 'nirier' },
  { value: '乍得', label: '乍得', flag: '🇹🇩', code: '+235', en: 'Chad', py: 'zhade' },
  { value: '卢旺达', label: '卢旺达', flag: '🇷🇼', code: '+250', en: 'Rwanda', py: 'luwangda' },
  { value: '几内亚', label: '几内亚', flag: '🇬🇳', code: '+224', en: 'Guinea', py: 'jineiya' },
  { value: '吉尔吉斯斯坦', label: '吉尔吉斯斯坦', flag: '🇰🇬', code: '+996', en: 'Kyrgyzstan', py: 'jierjisistan' },
  { value: '毛里求斯', label: '毛里求斯', flag: '🇲🇺', code: '+230', en: 'Mauritius', py: 'maoliqiusi' },
  { value: '加蓬', label: '加蓬', flag: '🇬🇦', code: '+241', en: 'Gabon', py: 'jiapeng' },
  { value: '纳米比亚', label: '纳米比亚', flag: '🇳🇦', code: '+264', en: 'Namibia', py: 'namibiya' },
  { value: '海地', label: '海地', flag: '🇭🇹', code: '+509', en: 'Haiti', py: 'haidi' },
  { value: '塔吉克斯坦', label: '塔吉克斯坦', flag: '🇹🇯', code: '+992', en: 'Tajikistan', py: 'tajikesitan' },
  { value: '巴布亚新几内亚', label: '巴布亚新几内亚', flag: '🇵🇬', code: '+675', en: 'Papua New Guinea', py: 'babuyaxinjineiya' },
  { value: '布基纳法索', label: '布基纳法索', flag: '🇧🇫', code: '+226', en: 'Burkina Faso', py: 'bujinafasuo' },
  { value: '贝宁', label: '贝宁', flag: '🇧🇯', code: '+229', en: 'Benin', py: 'beining' },
  { value: '马拉维', label: '马拉维', flag: '🇲🇼', code: '+265', en: 'Malawi', py: 'malawei' },
  { value: '马耳他', label: '马耳他', flag: '🇲🇹', code: '+356', en: 'Malta', py: 'maerta' },
  { value: '索马里', label: '索马里', flag: '🇸🇴', code: '+252', en: 'Somalia', py: 'suomali' },
  { value: '巴哈马', label: '巴哈马', flag: '🇧🇸', code: '+1-242', en: 'Bahamas', py: 'bahama' },
  { value: '黑山', label: '黑山', flag: '🇲🇪', code: '+382', en: 'Montenegro', py: 'heishan' },
  { value: '多哥', label: '多哥', flag: '🇹🇬', code: '+228', en: 'Togo', py: 'duoge' },
  { value: '毛里塔尼亚', label: '毛里塔尼亚', flag: '🇲🇷', code: '+222', en: 'Mauritania', py: 'maolitaniya' },
  { value: '斯威士兰', label: '斯威士兰', flag: '🇸🇿', code: '+268', en: 'Eswatini', py: 'siweishilan' },
  { value: '圭亚那', label: '圭亚那', flag: '🇬🇾', code: '+592', en: 'Guyana', py: 'guiyana' },
  { value: '马尔代夫', label: '马尔代夫', flag: '🇲🇻', code: '+960', en: 'Maldives', py: 'maerdaifu' },
  { value: '布隆迪', label: '布隆迪', flag: '🇧🇮', code: '+257', en: 'Burundi', py: 'bulongdi' },
  { value: '苏里南', label: '苏里南', flag: '🇸🇷', code: '+597', en: 'Suriname', py: 'sulinan' },
  { value: '不丹', label: '不丹', flag: '🇧🇹', code: '+975', en: 'Bhutan', py: 'budan' },
  { value: '利比里亚', label: '利比里亚', flag: '🇱🇷', code: '+231', en: 'Liberia', py: 'libiliya' },
  { value: '莱索托', label: '莱索托', flag: '🇱🇸', code: '+266', en: 'Lesotho', py: 'laisuotuo' },
  { value: '吉布提', label: '吉布提', flag: '🇩🇯', code: '+253', en: 'Djibouti', py: 'jibuti' },
  { value: '中非共和国', label: '中非共和国', flag: '🇨🇫', code: '+236', en: 'Central African Republic', py: 'zhongfei' },
  { value: '佛得角', label: '佛得角', flag: '🇨🇻', code: '+238', en: 'Cape Verde', py: 'fodejiao' },
  { value: '冈比亚', label: '冈比亚', flag: '🇬🇲', code: '+220', en: 'Gambia', py: 'gangbiya' },
  { value: '圣卢西亚', label: '圣卢西亚', flag: '🇱🇨', code: '+1-758', en: 'Saint Lucia', py: 'shenglucixiya' },
  { value: '安提瓜和巴布达', label: '安提瓜和巴布达', flag: '🇦🇬', code: '+1-268', en: 'Antigua and Barbuda', py: 'antigua' },
  { value: '几内亚比绍', label: '几内亚比绍', flag: '🇬🇼', code: '+245', en: 'Guinea-Bissau', py: 'jineiyabishao' },
  { value: '所罗门群岛', label: '所罗门群岛', flag: '🇸🇧', code: '+677', en: 'Solomon Islands', py: 'suoluomen' },
  { value: '塞舌尔', label: '塞舌尔', flag: '🇸🇨', code: '+248', en: 'Seychelles', py: 'saisheer' },
  { value: '格林纳达', label: '格林纳达', flag: '🇬🇩', code: '+1-473', en: 'Grenada', py: 'gelinnada' },
  { value: '科摩罗', label: '科摩罗', flag: '🇰🇲', code: '+269', en: 'Comoros', py: 'kemoluo' },
  { value: '圣基茨和尼维斯', label: '圣基茨和尼维斯', flag: '🇰🇳', code: '+1-869', en: 'Saint Kitts and Nevis', py: 'shengjici' },
  { value: '瓦努阿图', label: '瓦努阿图', flag: '🇻🇺', code: '+678', en: 'Vanuatu', py: 'wanuatu' },
  { value: '萨摩亚', label: '萨摩亚', flag: '🇼🇸', code: '+685', en: 'Samoa', py: 'samoya' },
  { value: '圣文森特和格林纳丁斯', label: '圣文森特和格林纳丁斯', flag: '🇻🇨', code: '+1-784', en: 'Saint Vincent and the Grenadines', py: 'shengwensente' },
  { value: '多米尼克', label: '多米尼克', flag: '🇩🇲', code: '+1-767', en: 'Dominica', py: 'duominike' },
  { value: '汤加', label: '汤加', flag: '🇹🇴', code: '+676', en: 'Tonga', py: 'tangjia' },
  { value: '圣多美和普林西比', label: '圣多美和普林西比', flag: '🇸🇹', code: '+239', en: 'Sao Tome and Principe', py: 'shengduomei' },
  { value: '密克罗尼西亚', label: '密克罗尼西亚', flag: '🇫🇲', code: '+691', en: 'Micronesia', py: 'mikeluonixiya' },
  { value: '帕劳', label: '帕劳', flag: '🇵🇼', code: '+680', en: 'Palau', py: 'palao' },
  { value: '马绍尔群岛', label: '马绍尔群岛', flag: '🇲🇭', code: '+692', en: 'Marshall Islands', py: 'mashaoer' },
  { value: '基里巴斯', label: '基里巴斯', flag: '🇰🇮', code: '+686', en: 'Kiribati', py: 'jilibasi' },
  { value: '瑙鲁', label: '瑙鲁', flag: '🇳🇷', code: '+674', en: 'Nauru', py: 'naolu' },
  { value: '图瓦卢', label: '图瓦卢', flag: '🇹🇻', code: '+688', en: 'Tuvalu', py: 'tuwalu' },
  { value: '梵蒂冈', label: '梵蒂冈', flag: '🇻🇦', code: '+39', en: 'Vatican City', py: 'fandigang' },
  { value: '摩纳哥', label: '摩纳哥', flag: '🇲🇨', code: '+377', en: 'Monaco', py: 'monage' },
  { value: '列支敦士登', label: '列支敦士登', flag: '🇱🇮', code: '+423', en: 'Liechtenstein', py: 'liezhidunshideng' },
  { value: '圣马力诺', label: '圣马力诺', flag: '🇸🇲', code: '+378', en: 'San Marino', py: 'shengmalinuo' },
  { value: '安道尔', label: '安道尔', flag: '🇦🇩', code: '+376', en: 'Andorra', py: 'andaoer' },
  { value: '朝鲜', label: '朝鲜', flag: '🇰🇵', code: '+850', en: 'North Korea', py: 'chaoxian' },
  { value: '叙利亚', label: '叙利亚', flag: '🇸🇾', code: '+963', en: 'Syria', py: 'xuliya' },
  { value: '南苏丹', label: '南苏丹', flag: '🇸🇸', code: '+211', en: 'South Sudan', py: 'nansudan' },
  { value: '苏丹', label: '苏丹', flag: '🇸🇩', code: '+249', en: 'Sudan', py: 'sudan' },
  { value: '刚果（布）', label: '刚果（布）', flag: '🇨🇬', code: '+242', en: 'Republic of the Congo', py: 'gangguobu' },
  { value: '厄立特里亚', label: '厄立特里亚', flag: '🇪🇷', code: '+291', en: 'Eritrea', py: 'eliteliya' },
  { value: '特立尼达和多巴哥', label: '特立尼达和多巴哥', flag: '🇹🇹', code: '+1-868', en: 'Trinidad and Tobago', py: 'telinida' },
  { value: '伯利兹', label: '伯利兹', flag: '🇧🇿', code: '+501', en: 'Belize', py: 'bolizi' },
  { value: '巴巴多斯', label: '巴巴多斯', flag: '🇧🇧', code: '+1-246', en: 'Barbados', py: 'babaduosi' },
  { value: '东帝汶', label: '东帝汶', flag: '🇹🇱', code: '+670', en: 'Timor-Leste', py: 'dongdiwen' },
  { value: '赤道几内亚', label: '赤道几内亚', flag: '🇬🇶', code: '+240', en: 'Equatorial Guinea', py: 'chidaojineiya' },
  { value: '谢拉利昂', label: '谢拉利昂', flag: '🇸🇱', code: '+232', en: 'Sierra Leone', py: 'xielalieang' },
];
